name: Code Improvement

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort

      - name: Run flake8
        run: flake8 .

      - name: Run isort
        run: isort --check-only --diff .

      - name: Run black
        run: black --check .

      - name: Auto format code
        run: |
          isort .
          black .
        if: github.event_name == 'push'

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: auto format code with isort and black"
          branch: main
          file_pattern: |
            **/*.py
